### ISSUE TITLE
Панель автопрокрутки

### ISSUE THREAD

**Issue by ekorolev** [ekorolev/pesennik#3]
Сделать панель автопрокрутки с фиксированной позицией с элементами: ускорение автопрокрутки, замедление, остановка.

**Comment by alekskorolev** [comment]
есть еще предложение сделать запоминание последней скорости для песни, что-бы каждый раз не регулировать. либо костылем через браузерное хранилище, либо с сохранением в базу.

**Comment by ekorolev** [comment]
Поддерживаю

**Comment by ekorolev** [comment]
Панель автопрокрутки есть, добавил ее в продакшн. Осталось три момента, вынесу их в отдельные задачи.

alekskorolev, спасибо :)
