### ISSUE TITLE
Импорт данных "на лету"

### ISSUE THREAD

**Issue by ekorolev** [ekorolev/pesennik#4]
При добавлении ссылки на сторонний ресурс на странице добавления новой песни импортировать и автозаполнять данные сразу, чтобы предоставить возможность отредактировать их.

**Comment by alekskorolev** [comment]
еще, если мы не даем редактировать исполнителя после добавления, надо не давать сохранять пока поле не заполнено. просто непонятно, добавил я ошибочно исполнителя пустого а изменить не могу. 
а еще такой сценарий, я ошибся первой буквой.. все песни у меня к исполнителю Агата Кристи, одну добавил как Ягата Кристи.. и между ними весь алфавит.

**Comment by ekorolev** [comment]
Сделал.

Выношу задачу на добавление новых сторонних ресурсов для импорта.
